name: lazy-split

# add your pipline description below
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.7.1'

      - name: Install dependencies
        run: poetry install
      
      - name: Formatting with Black
        run: poetry run black app front

      - name: Linting wiht Flake8
        run: poetry run flake8 --ignore=F403,F401,W503 app front
      
      - name: Run tests
        run: poetry run pytest --cov app/ --cov-branch --cov-report=term --cov-fail-under=85

      - name: Run bandit
        run: poetry run bandit app